spring:
  profiles:
    active: local, dev, qa, prod, test
  main: 
    banner-mode: off
  devtools:
    livereload:
      enabled: false
  neo4j:
    authentication:
      username: neo4j
    uri: bolt://localhost:7687
command:
  deleteArtifacts:
    enabled: true
  deleteTechniques: 
    enabled: true
  deleteDetections: 
    enabled: true
  deleteInferences: 
    enabled: true
  deleteFindings: 
    enabled: true