spring:
  devtools:
    livereload:
      enabled: false
  neo4j:
    authentication:
      password: P@55w0rd!
      username: neo4j
    uri: bolt://localhost:7687
command:
  deleteEvents:
    enabled: true
  deleteTechniques: 
    enabled: true