spring:
  devtools:
    livereload:
      enabled: false
  neo4j:
    authentication:
      password: tbd
      username: tbd
    uri: bolt://localhost:7687
command:
  deleteEvents:
    enabled: true
  deleteTechniques: 
    enabled: true