spring:
  main: 
    banner-mode: off
  devtools:
    livereload:
      enabled: false
  neo4j:
    authentication:
      username: neo4j
    uri: bolt://localhost:7687
command:
  deleteEvents:
    enabled: true
  deleteTechniques: 
    enabled: true